### ISSUE TITLE
Boost::filesystem3 error

### ISSUE THREAD

**Issue by siddahuja** [strasdat/ScaViSLAM#19]
Hey

I got everything else to compile and build with no issues, except when i got to building the scavislam package.

Here is the error trace:

$ cmake ..
CUDA SUPPORT ON
PCL SUPPORT OFF
SSE 4.1  SUPPORT OFF
-- found library 'GL': /usr/lib/libGL.so
-- found library 'pangolin': /home/sid/ScaViSLAM/EXTERNAL/Pangolin/svs_build/pangolin/libpangolin.so
-- found library 'glut': /usr/lib/libglut.so
-- found library 'g2o_stuff': /home/sid/ScaViSLAM/EXTERNAL/g2o/lib/libg2o_stuff.so
-- found library 'g2o_core': /home/sid/ScaViSLAM/EXTERNAL/g2o/lib/libg2o_core.so
-- found library 'g2o_solver_csparse': /home/sid/ScaViSLAM/EXTERNAL/g2o/lib/libg2o_solver_csparse.so
-- found library 'VisionTools': /home/sid/ScaViSLAM/EXTERNAL/VisionTools/svs_build/libVisionTools.so
-- found library 'Sophus': /home/sid/ScaViSLAM/EXTERNAL/Sophus/svs_build/libSophus.so
-- found library 'boost_system': /usr/lib/libboost_system.so
-- found library 'boost_thread': /usr/lib/libboost_thread.so
-- found library 'boost_filesystem': /usr/lib/libboost_filesystem.so
-- found library 'boost_regex': /usr/lib/libboost_regex.so
-- found library 'opencv_core': /home/sid/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_core.so
-- found library 'opencv_features2d': /home/sid/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_features2d.so
-- found library 'opencv_flann': /home/sid/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_flann.so
-- found library 'opencv_gpu': /home/sid/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_gpu.so
-- found library 'opencv_highgui': /home/sid/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_highgui.so
-- found library 'opencv_imgproc': /home/sid/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_imgproc.so
-- found library 'opencv_calib3d': /home/sid/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib/libopencv_calib3d.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sid/ScaViSLAM/svs_build

$ make -j8
/usr/bin/cmake -H/home/sid/ScaViSLAM -B/home/sid/ScaViSLAM/svs_build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/sid/ScaViSLAM/svs_build/CMakeFiles /home/sid/ScaViSLAM/svs_build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/sid/ScaViSLAM/svs_build'
make -f CMakeFiles/ScaViSLAM.dir/build.make CMakeFiles/ScaViSLAM.dir/depend
make[2]: Entering directory`/home/sid/ScaViSLAM/svs_build'
cd /home/sid/ScaViSLAM/svs_build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/sid/ScaViSLAM /home/sid/ScaViSLAM /home/sid/ScaViSLAM/svs_build /home/sid/ScaViSLAM/svs_build /home/sid/ScaViSLAM/svs_build/CMakeFiles/ScaViSLAM.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/sid/ScaViSLAM/svs_build'
make -f CMakeFiles/ScaViSLAM.dir/build.make CMakeFiles/ScaViSLAM.dir/build
make[2]: Entering directory`/home/sid/ScaViSLAM/svs_build'
Linking CXX shared library libScaViSLAM.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/ScaViSLAM.dir/link.txt --verbose=1
/usr/bin/c++  -fPIC -O3 -g  -shared -Wl,-soname,libScaViSLAM.so -o libScaViSLAM.so CMakeFiles/ScaViSLAM.dir/scavislam/placerecognizer.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/maths_utils.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/ransac_models.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/homography.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/g2o_types/anchored_points.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/stereo_camera.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/backend.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/fast_grid.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/stereo_frontend.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/dense_tracking.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/filegrabber.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/ransac.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/ransac-impl.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/frame_grabber.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/frame_grabber-impl.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/matcher.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/matcher-impl.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/slam_graph.cpp.o CMakeFiles/ScaViSLAM.dir/scavislam/slam_graph-impl.cpp.o ./ScaViSLAM_generated_dense_tracking.cu.o -lGL ../EXTERNAL/Pangolin/svs_build/pangolin/libpangolin.so -lglut ../EXTERNAL/g2o/lib/libg2o_stuff.so ../EXTERNAL/g2o/lib/libg2o_core.so ../EXTERNAL/g2o/lib/libg2o_solver_csparse.so ../EXTERNAL/VisionTools/svs_build/libVisionTools.so ../EXTERNAL/Sophus/svs_build/libSophus.so -lboost_system -lboost_thread -lboost_filesystem -lboost_regex ../EXTERNAL/opencv2/svs_build/lib/libopencv_core.so ../EXTERNAL/opencv2/svs_build/lib/libopencv_features2d.so ../EXTERNAL/opencv2/svs_build/lib/libopencv_flann.so ../EXTERNAL/opencv2/svs_build/lib/libopencv_gpu.so ../EXTERNAL/opencv2/svs_build/lib/libopencv_highgui.so ../EXTERNAL/opencv2/svs_build/lib/libopencv_imgproc.so ../EXTERNAL/opencv2/svs_build/lib/libopencv_calib3d.so /usr/local/cuda/lib64/libcudart.so -lcuda -Wl,-rpath,/home/sid/ScaViSLAM/EXTERNAL/Pangolin/svs_build/pangolin:/home/sid/ScaViSLAM/EXTERNAL/g2o/lib:/home/sid/ScaViSLAM/EXTERNAL/VisionTools/svs_build:/home/sid/ScaViSLAM/EXTERNAL/Sophus/svs_build:/home/sid/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib:/usr/local/cuda/lib64 
make[2]: Leaving directory `/home/sid/ScaViSLAM/svs_build'
/usr/bin/cmake -E cmake_progress_report /home/sid/ScaViSLAM/svs_build/CMakeFiles  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
[ 90%] Built target ScaViSLAM
make -f CMakeFiles/create_dictionary.dir/build.make CMakeFiles/create_dictionary.dir/depend
make -f CMakeFiles/stereo_slam.dir/build.make CMakeFiles/stereo_slam.dir/depend
make[2]: Entering directory`/home/sid/ScaViSLAM/svs_build'
cd /home/sid/ScaViSLAM/svs_build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/sid/ScaViSLAM /home/sid/ScaViSLAM /home/sid/ScaViSLAM/svs_build /home/sid/ScaViSLAM/svs_build /home/sid/ScaViSLAM/svs_build/CMakeFiles/create_dictionary.dir/DependInfo.cmake --color=
make[2]: Entering directory `/home/sid/ScaViSLAM/svs_build'
cd /home/sid/ScaViSLAM/svs_build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/sid/ScaViSLAM /home/sid/ScaViSLAM /home/sid/ScaViSLAM/svs_build /home/sid/ScaViSLAM/svs_build /home/sid/ScaViSLAM/svs_build/CMakeFiles/stereo_slam.dir/DependInfo.cmake --color=
make[2]: Leaving directory`/home/sid/ScaViSLAM/svs_build'
make -f CMakeFiles/create_dictionary.dir/build.make CMakeFiles/create_dictionary.dir/build
make[2]: Entering directory `/home/sid/ScaViSLAM/svs_build'
/usr/bin/cmake -E cmake_progress_report /home/sid/ScaViSLAM/svs_build/CMakeFiles 21
[ 95%] make[2]: Leaving directory`/home/sid/ScaViSLAM/svs_build'
make -f CMakeFiles/stereo_slam.dir/build.make CMakeFiles/stereo_slam.dir/build
Building CXX object CMakeFiles/create_dictionary.dir/scavislam/create_dictionary.cpp.o
/usr/bin/c++   -DSCAVISLAM_CUDA_SUPPORT -DCUDA_BUILD -DBT_USE_DOUBLE_PRECISION -O3 -g -I/usr/local/cuda/include -I/home/sid/ScaViSLAM/EXTERNAL/eigen3.1 -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/include/opencv -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/include -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/modules/core/include -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/modules/imgproc/include -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/modules/video/include -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/modules/features2d/include -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/modules/flann/include -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/modules/objdetect/include -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/modules/calib3d/include -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/modules/ml/include -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/modules/highgui/include -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/modules/legacy/include -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/modules/contrib/include -I/home/sid/ScaViSLAM/EXTERNAL/g2o/svs_build -I/home/sid/ScaViSLAM/EXTERNAL/g2o -I/home/sid/ScaViSLAM/EXTERNAL/g2o/EXTERNAL/csparse -I/home/sid/ScaViSLAM/EXTERNAL/Pangolin -I/home/sid/ScaViSLAM/EXTERNAL/Pangolin/svs_build -I/home/sid/ScaViSLAM/EXTERNAL/Sophus -I/home/sid/ScaViSLAM/EXTERNAL/VisionTools -I/home/sid/ScaViSLAM/EXTERNAL/opencv2/modules/gpu/include -I/home/sid/NVIDIA_GPU_Computing_SDK/C/common/inc   -Wall -Werror -Wno-unused-variable                    -Wno-unused-but-set-variable -Wno-unknown-pragmas -o CMakeFiles/create_dictionary.dir/scavislam/create_dictionary.cpp.o -c /home/sid/ScaViSLAM/scavislam/create_dictionary.cpp
make[2]: Entering directory `/home/sid/ScaViSLAM/svs_build'
Linking CXX executable stereo_slam
/usr/bin/cmake -E cmake_link_script CMakeFiles/stereo_slam.dir/link.txt --verbose=1
/usr/bin/c++   -O3 -g   CMakeFiles/stereo_slam.dir/scavislam/stereo_slam.cpp.o  -o stereo_slam -rdynamic libScaViSLAM.so -lGL ../EXTERNAL/Pangolin/svs_build/pangolin/libpangolin.so -lglut ../EXTERNAL/g2o/lib/libg2o_stuff.so ../EXTERNAL/g2o/lib/libg2o_core.so ../EXTERNAL/g2o/lib/libg2o_solver_csparse.so ../EXTERNAL/VisionTools/svs_build/libVisionTools.so ../EXTERNAL/Sophus/svs_build/libSophus.so -lboost_system -lboost_thread -lboost_filesystem -lboost_regex ../EXTERNAL/opencv2/svs_build/lib/libopencv_core.so ../EXTERNAL/opencv2/svs_build/lib/libopencv_features2d.so ../EXTERNAL/opencv2/svs_build/lib/libopencv_flann.so ../EXTERNAL/opencv2/svs_build/lib/libopencv_gpu.so ../EXTERNAL/opencv2/svs_build/lib/libopencv_highgui.so ../EXTERNAL/opencv2/svs_build/lib/libopencv_imgproc.so ../EXTERNAL/opencv2/svs_build/lib/libopencv_calib3d.so /usr/local/cuda/lib64/libcudart.so -lcuda -Wl,-rpath,/home/sid/ScaViSLAM/svs_build:/home/sid/ScaViSLAM/EXTERNAL/Pangolin/svs_build/pangolin:/home/sid/ScaViSLAM/EXTERNAL/g2o/lib:/home/sid/ScaViSLAM/EXTERNAL/VisionTools/svs_build:/home/sid/ScaViSLAM/EXTERNAL/Sophus/svs_build:/home/sid/ScaViSLAM/EXTERNAL/opencv2/svs_build/lib:/usr/local/cuda/lib64 
make[2]: Leaving directory`/home/sid/ScaViSLAM/svs_build'
/usr/bin/cmake -E cmake_progress_report /home/sid/ScaViSLAM/svs_build/CMakeFiles  22
[100%] Built target stereo_slam
/home/sid/ScaViSLAM/scavislam/create_dictionary.cpp: In function ‘std::liststd::basic_string<char > preprocessFiles(const boost::filesystem::path&)’:
/home/sid/ScaViSLAM/scavislam/create_dictionary.cpp:47:16: error: ‘boost::filesystem3’ has not been declared
/home/sid/ScaViSLAM/scavislam/create_dictionary.cpp:47:35: error: expected ‘;’ before ‘name’
/home/sid/ScaViSLAM/scavislam/create_dictionary.cpp:48:29: error: ‘name’ was not declared in this scope
cc1plus: warnings being treated as errors
At global scope:
cc1plus: error: unrecognized command line option "-Wno-unused-but-set-variable"
make[2]: **\* [CMakeFiles/create_dictionary.dir/scavislam/create_dictionary.cpp.o] Error 1
make[2]: Leaving directory `/home/sid/ScaViSLAM/svs_build'
make[1]: *** [CMakeFiles/create_dictionary.dir/all] Error 2
make[1]: Leaving directory`/home/sid/ScaViSLAM/svs_build'
make: **\* [all] Error 2

SO the error is in the create_dictionary.cpp file on Line 47. I believe someone accidently typed filesystem3 instead of filesystem. Changed that back to the name of filesystem (removing number 3) and rebuilt. Everything seems to build fine now.

**Comment by strasdat** [comment]
There were some recent API changes in boost. "filesystem3" should work, if you use a newer version of Boost.
